-- 1. Tabela de Feedback e Votação de Tópicos
CREATE TABLE public.site_feedback (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Pode ser anônimo
  preferred_topics TEXT[], -- Array de tópicos (ex: ['Tech', 'IA'])
  new_topic_suggestion TEXT,
  rating INT CHECK (rating >= 0 AND rating <= 5),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Logs de Acesso (Analytics)
CREATE TABLE public.access_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL, -- 'login', 'view_post', 'session_end'
  event_data JSONB, -- Dados flexíveis (ex: { "post_id": 123, "duration_seconds": 45 })
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Segurança (Permitir inserção pública para logs e feedback)
ALTER TABLE public.site_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_logs ENABLE ROW LEVEL SECURITY;

-- Política: Todos podem INSERIR dados (mesmo anônimos), mas ninguém lê via API (segurança BI)
CREATE POLICY "Enable insert for everyone" ON public.site_feedback FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for everyone" ON public.access_logs FOR INSERT WITH CHECK (true);