-- Criação da tabela de posts
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  summary TEXT, -- Um resumo curto para o cartão e twitter
  content TEXT NOT NULL, -- O HTML gerado pelo Gemini
  original_url TEXT NOT NULL UNIQUE, -- A chave de idempotência
  image_url TEXT, -- Capa da notícia (vindo da NewsAPI)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (Segurança)
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- Política: Qualquer pessoa pode LER (Select)
CREATE POLICY "Public posts are viewable by everyone" 
ON posts FOR SELECT USING (true);

-- Política: Apenas a Service Role (Backend) pode INSERIR/MODIFICAR
-- (Não precisamos criar policy explícita para service role, ela já tem bypass, 
-- mas isso garante que usuários anônimos não postem nada via API client-side).
