import Link from "next/link";
import { ThemeToggle } from "@/components/ThemeToggle";
import { FileText, ShieldAlert } from "lucide-react";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-zinc-50 dark:bg-black text-zinc-900 dark:text-green-500 font-mono p-4 md:p-12 transition-colors duration-300 selection:bg-green-500 selection:text-black">
      <div className="max-w-3xl mx-auto border border-zinc-200 dark:border-green-900 p-6 md:p-10 bg-white dark:bg-[#050505] shadow-sm relative">
        
        <div className="flex justify-between items-center mb-8 border-b border-zinc-200 dark:border-green-900/50 pb-4">
            <Link 
              href="/" 
              className="text-[10px] font-bold uppercase tracking-widest hover:text-zinc-500 dark:hover:text-green-300 transition-colors flex items-center gap-2"
            >
              &lt;&lt; ABORT_AND_RETURN
            </Link>
            <ThemeToggle />
        </div>

        <div className="mb-10">
            <div className="flex items-center gap-3 mb-2 text-zinc-400 dark:text-green-700">
                <FileText size={20} />
                <span className="text-xs uppercase tracking-widest">Legal_Document_01</span>
            </div>
            <h1 className="text-3xl md:text-4xl font-black uppercase tracking-tighter text-black dark:text-green-100">
                Terms of Service
            </h1>
            <p className="text-[10px] uppercase tracking-widest mt-2 opacity-60">Last_Updated: 2025-10-27</p>
        </div>

        <div className="space-y-8 text-sm leading-relaxed text-zinc-600 dark:text-green-400/90">
            <Section title="01. Protocol_Acceptance">
                By accessing the NovaPress network, you acknowledge that you are consuming content generated by an artificial intelligence. If the system hallucinates, please exercise biological common sense.
            </Section>

            <Section title="02. Data_Accuracy">
                Our generative models strive for precision, but glitches in the matrix may occur. Do not use this data for life-critical decisions, financial speculation, or interplanetary navigation.
            </Section>

            <Section title="03. Intellectual_Property">
                Original source materials belong to their respective biological entities. NovaPress acts as a summarization layer. If you own the source data and wish to terminate the link, transmit a DMCA packet.
            </Section>
            
            <Section title="04. Liability_Waiver">
                We provide this service "as is". We guarantee nothing except that the code was compiled with significant quantities of caffeine.
            </Section>

            <div className="mt-8 p-3 bg-red-50 dark:bg-red-900/10 border border-red-200 dark:border-red-900/30 text-red-600 dark:text-red-400 text-xs flex gap-3">
                <ShieldAlert size={16} className="shrink-0" />
                <span>WARNING: Unauthorized replication of this platform's source code will result in bad karma.</span>
            </div>
        </div>

        <div className="mt-12 pt-6 border-t border-dashed border-zinc-200 dark:border-green-900/50 text-[10px] uppercase tracking-widest opacity-50 text-center">
            End of File // Legal_Node
        </div>

      </div>
    </main>
  );
}

function Section({ title, children }: any) {
    return (
        <section>
            <h2 className="text-xs font-bold mb-2 uppercase text-black dark:text-green-300 flex items-center gap-2">
                <span className="text-blue-500 dark:text-green-600">&gt;</span>
                {title}
            </h2>
            <p className="pl-4 border-l border-zinc-200 dark:border-green-900">
                {children}
            </p>
        </section>
    )
}